---
name: DNF CI
on: pull_request_target

jobs:
  copr-build-dnf4:
    name: DNF4 Copr Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
    outputs:
      package-urls: ${{steps.copr-build.outputs.package-urls}}
    steps:
      - name: Check out ci-dnf-stack
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/ci-dnf-stack

      - name: Setup CI
        id: setup-ci
        uses: ./.github/actions/setup-ci
        with:
          copr-user: ${{secrets.COPR_USER}}
          copr-api-token: ${{secrets.COPR_API_TOKEN}}

      - name: Check out sources
        uses: actions/checkout@v2
        with:
          path: gits/${{github.event.repository.name}}
          ref: ${{github.event.pull_request.head.sha}}  # check out the PR HEAD
          fetch-depth: 0

      - name: Run Copr Build
        id: copr-build
        uses: ./.github/actions/copr-build
        with:
          copr-user: ${{steps.setup-ci.outputs.copr-user}}

  copr-build-dnf5:
    name: DNF5 Copr Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
    outputs:
      package-urls: ${{steps.copr-build.outputs.package-urls}}
    steps:
      - name: Check out ci-dnf-stack
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/ci-dnf-stack

      - name: Setup CI
        id: setup-ci
        uses: ./.github/actions/setup-ci
        with:
          copr-user: ${{secrets.COPR_USER}}
          copr-api-token: ${{secrets.COPR_API_TOKEN}}

      - name: Check out sources
        uses: actions/checkout@v2
        with:
          path: gits/${{github.event.repository.name}}
          ref: ${{github.event.pull_request.head.sha}}  # check out the PR HEAD
          fetch-depth: 0

      - name: Run Copr Build
        id: copr-build
        uses: ./.github/actions/copr-build
        with:
          copr-user: ${{steps.setup-ci.outputs.copr-user}}
          overlay: dnf5-ci

  integration-tests-dnf4:
    name: DNF4 Integration Tests
    needs: copr-build-dnf4
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
      options: --privileged
    steps:
      - name: Check out ci-dnf-stack
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/ci-dnf-stack
          ref: dnf-4-stack

      - name: Run Integration Tests
        uses: ./.github/actions/integration-tests
        with:
          package-urls: ${{needs.copr-build-dnf4.outputs.package-urls}}

  integration-tests-dnf5:
    name: DNF5 Integration Tests
    needs: copr-build-dnf5
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
      options: --privileged
    strategy:
      matrix:
        extra-run-args: [--tags dnf5 --command dnf5, --tags dnf5daemon --command dnf5daemon-client]
    steps:
      - name: Check out ci-dnf-stack
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/ci-dnf-stack

      - name: Run Integration Tests
        uses: ./.github/actions/integration-tests
        with:
          package-urls: ${{needs.copr-build-dnf5.outputs.package-urls}}
          extra-run-args: ${{matrix.extra-run-args}}

  ansible-tests:
    name: Ansible Tests
    needs: copr-build-dnf4
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
      options: --privileged
    steps:
      - name: Check out ci-dnf-stack
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/ci-dnf-stack

      - name: Run Ansible Tests
        uses: ./.github/actions/ansible-tests
        with:
          package-urls: ${{needs.copr-build.outputs.package-urls}}
